type User {
    id: ID!
    email: String!
}

type Workout {
    date: Time!
    email: String!
    exercises: String!
}

type Query {
    allWorkouts: [Workout!]
    findWorkoutsByEmail(email: String!): [Workout!]
    getUserById(id: ID!): User!
    getUserByEmail(email: String!): User!
}
